### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by jokoho48** [jokoho48/AWPublicMission#80]
- [x] add Vehicels to the Vehicle Spawner
- [x] improve some Loadouts
  - [x] change Optics to a Black one
  - [x] add Secoundary Optics to some loadouts
  - [x] change Basic Camo Pattern?
- [x] Reconfigure Crates
- [ ] Test Mission!!!!!
  - [ ] Test New Loadouts and Crates
  - [ ] Test the CUP Vehicles
  - [x] ~~Test the CUP Static Weapons spawned in Towns~~ Buged need to replace with Vanilla
  - [ ] Test Ari
- [x] Repack and Sign Comp Mod
- [ ] properly add stoffl´s RH weapons comp patch mod(depend on current status)

**Comment by jokoho48** [comment]
Vests and Uniform Camo pattern change done

**Comment by F4BI** [comment]
Because we already had relaunch, please check the status.
